version: '2'

services:
  webapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webapp
    command: ./run_fir.sh
    volumes:
      - .:/app/FIR
    expose:
      - "8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    env_file:
      - ./mysql.env

  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    hostname: nginx
    volumes:
      - /www/static
    volumes_from:
      - webapp
    ports:
      - "80:80"
    links:
      - webapp:webapp

  db:
    image: mysql:5.7
    hostname: db
    volumes:
      - mysqldata:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./mysql.env

  redis:
    image: redis:3.2.5
    hostname: redis
    volumes:
      - redisdata:/var/lib/redis/data
    expose:
      - "6379"

  workers:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app/FIR
    links:
      - redis
    depends_on:
      - redis

volumes:
    redisdata:
    mysqldata:
