version: '2'

services:
  fir:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: fir
    command: ./run_fir.sh
    volumes:
      - .:/app/FIR
    ports:
      - "8000:8000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    hostname: nginx
    volumes:
      - /www/static
    volumes_from:
      - fir
    links:
      - fir

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env

  redis:
    image: redis:3.2.5
    hostname: redis
    ports:
      - "6379:6379"

  workers:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app/FIR
    links:
      - redis
    depends_on:
      - redis
